### ISSUE TITLE
No weightfiles provided in the folder

### ISSUE THREAD

**Issue by GitHubZhangpy** [kbitr/Matlab-YOLOv2-LiveTracking#2]
Hello, when I run 'mainFile.m', 'weightfile' used for initializing yolo can not find in the repository. Could you provide the weightfile for me? Thank you for your help :)

**Comment by kbitr** [comment]
That's all on the official website:

https://pjreddie.com/darknet/yolo/

**Comment by GitHubZhangpy** [comment]
Thanks for your guidance. The code works well :)
By the way, does the code support yolo v3? 
When I change the configure file and model to yolo v3, Matlab crashed and said:
'Layer before convolutional layer must output image.: File exists
MATLAB: ./darknet/src/utils.c:224: error: Assertion `0' failed.'

**Comment by kbitr** [comment]
I have never tried yolo v3 as it wasn't released when I worked on this project. When you port it to v3 you are of course invited to merge!
